
#This is the DLC(Spaced Out) configuration file


#Printing Pod seconds per cycle,The game default value is 1800 seconds (TimeBeforeSpawn: Must be a positive integer)
TimeBeforeSpawn = 900


#Blueprint setting,DuplicantNumber:duplicant optional number, CarePackageNumber: carepackage optional number,Value limit：DuplicantNumber + CarePackageNumber <= 10
DuplicantNumber = 3
CarePackageNumber = 1


#Interests setting,InterestNumber：number of interest,Value limit: 0 to 13 ; InterestValue:number of interest values, Value limit：0 to 1000
InterestNumber = 2
InterestValue = 25


#Traits setting,PositiveTraitsNumber:number of good traits,NegativeTraitsNumber:number of bad traits,PositiveTraitsNumber value limit：0 to 34,NegativeTraitsNumber value limit：0 to 28
PositiveTraitsNumber = 3
NegativeTraitsNumber = 0


#Stress Reaction setting,Stress:stress reaction list,One of them is randomly selected,If there is only one, the value is required
Stress = Aggressive,StressVomiter,UglyCrier,BingeEater


#Overjoyed Response setting，Overjoyed：overjoyed response list,One of them is randomly selected,If there is only one, the value is required
Overjoyed = BalloonArtist,SparkleStreaker,StickerBomber,SuperProductive
#Overjoyed = SuperProductive





